# Reconhecimento dos Dados — Atividade 1

Este notebook inspeciona o arquivo bruto `Dados - Atividade 1.xlsx` antes de qualquer limpeza:

1. **Carregamento e inspeção inicial** — shape, amostra e tipos de cada aba, estatísticas descritivas
2. **Diagnóstico de qualidade** — nulos, duplicatas, sobreposição de CPFs entre abas e valores únicos

In [10]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

FILE = 'Dados - Atividade 1.xlsx'

---
## 1. Carregamento e Inspeção Inicial

In [11]:
df_main = pd.read_excel(FILE, sheet_name='Tablib Dataset')
df_perf = pd.read_excel(FILE, sheet_name='performance')
df_area = pd.read_excel(FILE, sheet_name='área')

print(f'Tablib Dataset : {df_main.shape[0]:,} linhas x {df_main.shape[1]} colunas')
print(f'performance    : {df_perf.shape[0]:,} linhas x {df_perf.shape[1]} colunas')
print(f'área           : {df_area.shape[0]:,} linhas x {df_area.shape[1]} colunas')

Tablib Dataset : 4,281 linhas x 58 colunas
performance    : 2,382 linhas x 5 colunas
área           : 4,394 linhas x 2 colunas

In [4]:
df_main.head(3)

,Nome,Sobrenome,E-mail,CPF,Match,Potencial Bruto,Raciocínio,Social,Motivacional,Cultura pontuação,...,Início - Raciocínio,Fim - Raciocínio,Início - Cultura,Fim - Cultura,Início - Social,Fim - Social,Início - Motivacional,Fim - Motivacional,Início - Perfil,Fim - Perfil
0,Heloísa,Duartche,heloisaduarte7623@example.com,582.975.481-98,NaN,15.02,10.89,8.50,30.78,61.62,...,2019-08-21 16:35:33.827601+00:00,2019-09-02 18:47:40.230133+00:00,2018-06-12 13:50:12.544201+00:00,2019-09-02 18:45:58.610119+00:00,2019-08-21 16:36:46.205308+00:00,2019-09-02 18:47:52.188799+00:00,2017-10-02 21:37:08.829909+00:00,2017-10-02 21:37:55.440674+00:00,2019-09-02 18:48:52.221133+00:00,2019-09-02 18:49:55.512234+00:00
1,Sophia,Lima,sophialima1036@example.com,618.492.035-98,NaN,41.18,27.31,31.07,77.53,71.92,...,2017-03-11 00:47:44.258948+00:00,2017-03-11 01:36:09.837171+00:00,2017-03-11 04:39:17.036294+00:00,2017-03-11 04:44:18.962437+00:00,2017-03-11 05:08:18.867391+00:00,2017-03-11 05:22:52.602643+00:00,2017-03-11 04:55:58.406306+00:00,2017-03-11 05:06:41.817962+00:00,2017-03-11 04:46:18.698012+00:00,2017-03-11 04:52:43.434487+00:00
2,Cauã,Alves,cauaalves8382@example.com,376.104.598-11,NaN,56.78,71.39,47.53,46.36,49.10,...,2017-04-09 11:48:22.486594+00:00,2017-04-09 12:35:40.925275+00:00,2017-04-09 12:38:23.387423+00:00,2017-04-09 12:43:47.091106+00:00,2017-04-09 13:05:14.795158+00:00,2017-04-09 13:14:37.327611+00:00,2017-04-09 12:53:30.554098+00:00,2017-04-09 13:05:01.111152+00:00,2017-04-09 12:44:57.652249+00:00,2017-04-09 12:52:19.887744+00:00

In [12]:
print('=== performance (amostra) ===')
display(df_perf.head(3))

print('=== área (amostra) ===')
display(df_area.head(3))

=== performance (amostra) ===

,CPF,Performance 1º/2019,Performance 2º/2018,Performance 1º/2018,Performance 2º 2017
0,678.042.935-18,3.0,2.0,2.0,3.0
1,089.324.175-12,2.0,2.0,2.0,2.0
2,587.416.093-11,2.0,2.0,2.0,2.0

=== área (amostra) ===

              CPF       Área
0  582.975.481-98  Comercial
1  618.492.035-98  Logística
2  376.104.598-11  Comercial

In [5]:
df_main.dtypes

Nome                                       str
Sobrenome                                  str
E-mail                                     str
CPF                                        str
Match                                  float64
Potencial Bruto                        float64
Raciocínio                             float64
Social                                 float64
Motivacional                           float64
Cultura pontuação                      float64
Cultura classificação                      str
atributo-Capacidade analítica          float64
atributo-Pensamento conceitual         float64
atributo-Reflexão                      float64
atributo-Pensamento criativo           float64
atributo-Planejamento e organização    float64
atributo-Comunicação                   float64
atributo-Consideração pelos outros     float64
atributo-Influência                    float64
atributo-Sociabilidade                 float64
atributo-Facilitação                   float64
atributo-Flexibilidade                 float64
atributo-Estabilidade emocional        float64
atributo-Ambição                       float64
atributo-Iniciativa                    float64
atributo-Assertividade                 float64
atributo-Tomada de riscos              float64
perfil-Capacidade analítica            float64
perfil-Pensamento conceitual           float64
perfil-Reflexão                        float64
perfil-Pensamento criativo             float64
perfil-Planejamento e organização      float64
perfil-Comunicação                     float64
perfil-Consideração pelos outros       float64
perfil-Influência                      float64
perfil-Sociabilidade                   float64
perfil-Facilitação                     float64
perfil-Flexibilidade                   float64
perfil-Estabilidade emocional          float64
perfil-Ambição                         float64
perfil-Iniciativa                      float64
perfil-Assertividade                   float64
perfil-Tomada de riscos                float64
URL Raciocínio                             str
URL Cultura                                str
URL Social                                 str
URL Motivacional                           str
URL Perfil                                 str
Início - Raciocínio                        str
Fim - Raciocínio                           str
Início - Cultura                           str
Fim - Cultura                              str
Início - Social                            str
Fim - Social                               str
Início - Motivacional                      str
Fim - Motivacional                         str
Início - Perfil                            str
Fim - Perfil                               str
dtype: object

In [ ]:
cols_numericas = df_main.select_dtypes(include='number').columns.tolist()
df_main[cols_numericas].describe().round(2)

---
## 2. Diagnóstico de Qualidade

### 2.1 Valores nulos — Tablib Dataset

In [13]:
nulos = df_main.isnull().sum()
pct   = (nulos / len(df_main) * 100).round(1)
resumo_nulos = pd.DataFrame({'nulos': nulos, '% nulos': pct})
resumo_nulos[resumo_nulos['nulos'] > 0].sort_values('% nulos', ascending=False)

                                     nulos  % nulos
Match                                 4281    100.0
atributo-Comunicação                  3360     78.5
atributo-Tomada de riscos             3360     78.5
atributo-Assertividade                3360     78.5
atributo-Iniciativa                   3360     78.5
atributo-Ambição                      3360     78.5
atributo-Estabilidade emocional       3360     78.5
atributo-Flexibilidade                3360     78.5
atributo-Facilitação                  3360     78.5
atributo-Influência                   3360     78.5
atributo-Consideração pelos outros    3360     78.5
atributo-Sociabilidade                3360     78.5
atributo-Planejamento e organização   3360     78.5
atributo-Pensamento criativo          3360     78.5
atributo-Reflexão                     3360     78.5
atributo-Pensamento conceitual        3360     78.5
atributo-Capacidade analítica         3360     78.5
Potencial Bruto                       3353     78.3
Fim - Motivacional                    3325     77.7
Motivacional                          3325     77.7
Início - Motivacional                 3314     77.4
Social                                3300     77.1
Fim - Social                          3300     77.1
Início - Social                       3283     76.7
perfil-Facilitação                    3262     76.2
perfil-Tomada de riscos               3262     76.2
perfil-Assertividade                  3262     76.2
perfil-Iniciativa                     3262     76.2
perfil-Ambição                        3262     76.2
perfil-Estabilidade emocional         3262     76.2
perfil-Flexibilidade                  3262     76.2
perfil-Pensamento conceitual          3262     76.2
perfil-Sociabilidade                  3262     76.2
perfil-Pensamento criativo            3262     76.2
perfil-Capacidade analítica           3262     76.2
perfil-Influência                     3262     76.2
perfil-Reflexão                       3262     76.2
Fim - Perfil                          3262     76.2
perfil-Planejamento e organização     3262     76.2
perfil-Comunicação                    3262     76.2
perfil-Consideração pelos outros      3262     76.2
Início - Perfil                       3254     76.0
Fim - Raciocínio                      1060     24.8
Raciocínio                            1047     24.5
Fim - Cultura                          984     23.0
Cultura classificação                  970     22.7
Cultura pontuação                      970     22.7
Início - Cultura                       944     22.1
Início - Raciocínio                    773     18.1

### 2.2 Valores nulos — performance e área

In [14]:
print('=== performance ===')
print(df_perf.isnull().sum())
print('\n=== área ===')
print(df_area.isnull().sum())

=== performance ===
CPF                       0
Performance 1º/2019     835
Performance 2º/2018     805
Performance 1º/2018    1394
Performance 2º 2017    2029
dtype: int64

=== área ===
CPF     0
Área    0
dtype: int64

### 2.3 Duplicatas

In [15]:
print('Duplicatas Tablib Dataset (linhas completas):', df_main.duplicated().sum())
print('CPFs duplicados em Tablib Dataset           :', df_main['CPF'].duplicated().sum())
print('E-mails duplicados em Tablib Dataset        :', df_main['E-mail'].duplicated().sum())
print('CPFs duplicados em performance              :', df_perf['CPF'].duplicated().sum())
print('CPFs duplicados em área                     :', df_area['CPF'].duplicated().sum())

Duplicatas Tablib Dataset (linhas completas): 0
CPFs duplicados em Tablib Dataset           : 0
E-mails duplicados em Tablib Dataset        : 0
CPFs duplicados em performance              : 0
CPFs duplicados em área                     : 0

### 2.4 Sobreposição de CPFs entre as abas

Precisamos saber quantos cpf tem em cada aba para entender que tipo de join utilizar.

In [16]:
cpf_main = set(df_main['CPF'])
cpf_perf = set(df_perf['CPF'])
cpf_area = set(df_area['CPF'])

todas    = cpf_main & cpf_perf & cpf_area
so_main  = cpf_main - cpf_perf - cpf_area
so_perf  = cpf_perf - cpf_main
so_area  = cpf_area - cpf_main
main_sem_perf = cpf_main - cpf_perf
main_sem_area = cpf_main - cpf_area

print(f"CPFs no Tablib Dataset  : {len(cpf_main):,}")
print(f"CPFs em performance     : {len(cpf_perf):,}")
print(f"CPFs em área            : {len(cpf_area):,}")
print()
print(f"Nas três abas           : {len(todas):,}")
print(f"Tablib sem performance  : {len(main_sem_perf):,}  → ficam com NaN nos semestres")
print(f"Tablib sem área         : {len(main_sem_area):,}  → ficam sem área mapeada")
print(f"Performance sem Tablib  : {len(so_perf):,}  → perdidos no left join")
print(f"Área sem Tablib         : {len(so_area):,}  → perdidos no left join")

CPFs no Tablib Dataset  : 4,281
CPFs em performance     : 2,382
CPFs em área            : 4,394

Nas três abas           : 2,269
Tablib sem performance  : 2,012  → ficam com NaN nos semestres
Tablib sem área         : 0  → ficam sem área mapeada
Performance sem Tablib  : 113  → perdidos no left join
Área sem Tablib         : 113  → perdidos no left join

### 2.5 Valores únicos de colunas categóricas

In [17]:
print('Cultura classificação:', sorted(df_main['Cultura classificação'].dropna().unique()))
print('Área                 :', sorted(df_area['Área'].unique()))

Cultura classificação: ['Alto', 'Baixo', 'Muito alto', 'Muito baixo', 'Médio', 'Médio-alto', 'Médio-baixo']
Área                 : ['Comercial', 'Financeiro', 'Logística', 'Operações', 'Pessoas']

---
## 3. Executar Pipeline de Limpeza

Com o diagnóstico concluído, executar `limpeza_dados.py` para gerar o dataset limpo `dados_limpos.xlsx`.

In [1]:
%run limpeza_dados.py "Dados - Atividade 1.xlsx"

Tablib Dataset : 4,281 linhas x 58 colunas
performance    : 2,382 linhas x 5 colunas
área           : 4,394 linhas x 2 colunas
Match — % nula: 100.0 %
Colunas URL removidas: ['URL Raciocínio', 'URL Cultura', 'URL Social', 'URL Motivacional', 'URL Perfil']
Colunas de data convertidas: ['Início - Raciocínio', 'Fim - Raciocínio', 'Início - Cultura', 'Fim - Cultura', 'Início - Social', 'Fim - Social', 'Início - Motivacional', 'Fim - Motivacional', 'Início - Perfil', 'Fim - Perfil']
Flags criadas: ['fez_raciocinio', 'fez_cultura', 'fez_social', 'fez_motivacional', 'fez_perfil', 'fez_atributos']
Cultura classificação: {nan: 970, 'Medio-Baixo': 734, 'Baixo': 671, 'Medio': 636, 'Muito-Baixo': 474, 'Medio-Alto': 426, 'Alto': 245, 'Muito-Alto': 125}
Colunas performance: ['CPF', 'perf_1_2019', 'perf_2_2018', 'perf_1_2018', 'perf_2_2017']
Áreas: {'Operacoes': 1713, 'Comercial': 1590, 'Logistica': 919, 'Financeiro': 92, 'Pessoas': 80}
Linhas com CPF duplicado em área: 0

Dataset final: 4,281 linhas x 62 colunas
Candidatos com área mapeada: 4,281
Cobertura de performance por semestre:
  perf_1_2019: 1,456 (34.0%)
  perf_2_2018: 1,486 (34.7%)
  perf_1_2018: 988 (23.1%)
  perf_2_2017: 353 (8.2%)

Colunas com nulos no dataset final:
                                     nulos  % nulos
perf_2_2017                           3928     91.8
atributo-Pensamento criativo          3360     78.5
atributo-Facilitação                  3360     78.5
atributo-Sociabilidade                3360     78.5
atributo-Influência                   3360     78.5
atributo-Consideração pelos outros    3360     78.5
atributo-Comunicação                  3360     78.5
atributo-Planejamento e organização   3360     78.5
atributo-Reflexão                     3360     78.5
atributo-Estabilidade emocional       3360     78.5
atributo-Pensamento conceitual        3360     78.5
atributo-Capacidade analítica         3360     78.5
atributo-Ambição                      3360     78.5
atributo-Iniciativa                   3360     78.5
atributo-Assertividade                3360     78.5
atributo-Tomada de riscos             3360     78.5
atributo-Flexibilidade                3360     78.5
Potencial Bruto                       3353     78.3
Motivacional                          3325     77.7
Fim - Motivacional                    3325     77.7
Início - Motivacional                 3314     77.4
Social                                3300     77.1
Fim - Social                          3300     77.1
perf_1_2018                           3293     76.9
Início - Social                       3283     76.7
perfil-Iniciativa                     3262     76.2
perfil-Flexibilidade                  3262     76.2
Fim - Perfil                          3262     76.2
perfil-Tomada de riscos               3262     76.2
perfil-Assertividade                  3262     76.2
perfil-Ambição                        3262     76.2
perfil-Estabilidade emocional         3262     76.2
perfil-Planejamento e organização     3262     76.2
perfil-Facilitação                    3262     76.2
perfil-Sociabilidade                  3262     76.2
perfil-Capacidade analítica           3262     76.2
perfil-Pensamento conceitual          3262     76.2
perfil-Reflexão                       3262     76.2
perfil-Pensamento criativo            3262     76.2
perfil-Comunicação                    3262     76.2
perfil-Consideração pelos outros      3262     76.2
perfil-Influência                     3262     76.2
Início - Perfil                       3254     76.0
perf_1_2019                           2825     66.0
perf_2_2018                           2795     65.3
Fim - Raciocínio                      1061     24.8
Raciocínio                            1047     24.5
Fim - Cultura                          984     23.0
Cultura pontuação                      970     22.7
Cultura classificação                  970     22.7
Início - Cultura                       944     22.1
Início - Raciocínio                    774     18.1

Dataset exportado para "Dados - Atividade 1_limpo.xlsx" — 4,281 linhas x 62 colunas